#Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

#Production stage
FROM node:18-alpine AS production
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
COPY --from=build /app/dist ./dist
CMD ["sh", "-c", "npm run db:migrate && node dist/server.js"]